services:
  postgres:
    image: postgres:latest
    container_name: database
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  rabbit-mq:
    image: rabbitmq:4-management
    container_name: broker
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    environment:
      REDIS_HOST: cache
      REDIS_PORT: "6379"
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

volumes:
  postgres_database:
  rabbit_data:
  cache: